### ISSUE TITLE
new function table.move

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/lua-compat-5.3#3]
http://www.lua.org/manual/5.3/manual.html#pdf-table.move
> `table.move (a1, f, e, t [,a2])`

> Moves elements from table a1 to table a2. This function performs the equivalent to the following multiple assignment: a2[t],··· = a1[f],···,a1[e]. The default for a2 is a1. The destination range can overlap with the source range. Index f must be positive.

**Comment by siffiejoe** [comment]
`table.move` is available now.
