### ISSUE TITLE
luaL_loadbufferx

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/lua-compat-5.3#30]
The mode check can be implemented by checking if first character is `\x1b`. (that's what lua does internally via `LUA_SIGNATURE[0]`: http://www.lua.org/source/5.1/ldo.c.html#f_parser http://www.lua.org/source/5.3/ldo.c.html#f_parser)

Related to https://github.com/ThePhD/sol2/issues/508

**Comment by siffiejoe** [comment]
Closed with #34.
