### ISSUE TITLE
lua_getuservalue should return type

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/lua-compat-5.3#39]
We have a wrapper that works for 5.1, but 5.2 still returns `void`

**Comment by siffiejoe** [comment]
`lua_getuservalue` already returns the type of the uservalue even on Lua 5.2. See [here](https://github.com/keplerproject/lua-compat-5.3/blob/30077d241b788b644fb923b4c2da628cdd2c3423/c-api/compat-5.3.h#L348).

@daurnimator Do you have a specifiy case where it fails?

**Comment by daurnimator** [comment]
Ah no. I didn't notice the macro/wrapper.
