### ISSUE TITLE
Tests fail on 32bit systems

### ISSUE THREAD

**Issue by ConiKost** [keplerproject/lua-compat-5.3#49]
Running tests on ```amd64``` and ```arm64``` seems to run fine, but fail on ```arm``` and ```x86```. Do you have an idea, why?

```
lua: tests/test-bit32.lua:6: assertion failed!
stack traceback:
	[C]: in function 'assert'
	tests/test-bit32.lua:6: in main chunk
	[C]: ?
```

**Comment by siffiejoe** [comment]
This is the following test: `assert(bit32.bnot(0) == 2^32-1)`.

My first guess would be that maybe you have floats instead of doubles as `lua_Number`?! What Lua version are we talking about (and what is the size of `lua_Number`)? But it also could actually be a bug in the original code. Conversions between unsigned integers and doubles are tricky, and maybe no one tested the code on ARM, yet.

**Comment by ConiKost** [comment]
> What Lua version are we talking about (and what is the size of lua_Number)?

Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
How do I check ```lua_Number```?

**Comment by siffiejoe** [comment]
You can run `print(2^30 == 2^30+1)`. If it prints `true`, you have floats, otherwise you have doubles.

**Comment by ConiKost** [comment]
Allright, I've now tested on lua console:

```
> local bit32
> bit32 = require("bit32")
> print(bit32.bnot(0))
-1
```
Why does it give ```-1``` as value?

```
> print(2^30 == 2^30+1)
false
```

Funfact: on ```arm64``` everything is okay.

**Comment by ConiKost** [comment]
Running with lua5.2 (which as build in bit32?) does work fine on arm.
So it's related to this module and lua5.1 somehow.

**Comment by ConiKost** [comment]
There seems to be some sort of overflow? Limited to ```int32```?

```
> print(bit32.bnot(2147483649))
-2147483648
> print(bit32.bnot(-2147483649))
2147483647
```

**Comment by ConiKost** [comment]
I have to withdraw about ```x86```. It fails with the same error!
So basically bit32 seems to fail on 32bit systems (```arm```, ```x86```), while working on 64bit systems (```amd64```, ```arm64```)

**Comment by ConiKost** [comment]
Could be this related to newer versions? I noticed, that the ```compat52``` works with lua5.1 correctly, while ```compact53``` seems not?

**Comment by daurnimator** [comment]
How did you compile compat53? My hunch is that you've somehow gotten a luaconf.h from a different installation

**Comment by ConiKost** [comment]
Have a look into ```https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-lua/lua-bit32/lua-bit32-5.3.5.ebuild```.
I am running Gentoo here, but I am not the maintainer of that package. See ```src_compile```.

Can you see something?

> And how did you compile lua 5.1?

I can rule out, that this is related to lua5.1. If I take the precompiled bit32.so from Ubuntu (5.3.0, compat52) and replace my compiled bit32.so, everything works correctly!

**Comment by ConiKost** [comment]
I just recompiled (with the exact steps of the ebuild) ```lua-compat-5.2-bitlib-5.3.0```. All tests pass! This is also the version, which Ubuntu uses.

So it seems for me, something is broken with lua-compat-5.3-bitlib-0.9..

**Comment by siffiejoe** [comment]
The issue probably has to do with this macro: `#define pushunsigned(L,n)>lua_pushinteger(L, (lua_Integer)(n))` and `lua_Integer` being 32 bit in Lua 5.1 on 32 bit architectures. I just have to find a way to test/confirm and then fix this ...

**Comment by ConiKost** [comment]
Can I test something for you?

There seems to be a very similar problem: https://github.com/ThePhD/sol2/issues/470

**Comment by siffiejoe** [comment]
@ConiKost Yes, you can test the latest commit I just pushed.

If you are using LuaRocks, you can just execute `luarocks --dev install bit32`. Otherwise you probably already know what to do.

**Comment by ConiKost** [comment]
I can confirm, that you patch fixed it! All tests on ```arm```, ```arm64```, ```amd64``` and ```x86``` passed.
Will you make a new release?

**Comment by siffiejoe** [comment]
I did a release. I'm planning to add tests for 32bit architectures when I have more time.

**Comment by ConiKost** [comment]
Thanks!

**Comment by siffiejoe** [comment]
I've merged the bit32 tests on arm32 and am64 into master, so I'll close this issue now. If there is still something to be done, please reopen.

@keplerproject/team-lua-compat  I've also ported the previous Travis CI tests to GitHub Actions and disabled Travis CI for this repository because Travis has reduced its capacity for running open source jobs, and there currently is a backlog of over 4000. Test runs take hours to complete on Travis at the moment.
