### ISSUE TITLE
new functions lua_geti lua_seti

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/lua-compat-5.3#5]
http://www.lua.org/manual/5.3/manual.html#lua_geti

> `int lua_geti (lua_State *L, int index, lua_Integer i);`
>Pushes onto the stack the value t[i], where t is the value at the given index. As in Lua, this function may trigger a metamethod for the "index" event (see §2.4).
>
> Returns the type of the pushed value.

http://www.lua.org/manual/5.3/manual.html#lua_seti

> `void lua_seti (lua_State *L, int index, lua_Integer n);`
> Does the equivalent to t[n] = v, where t is the value at the given index and v is the value at the top of the stack.
>
> This function pops the value from the stack. As in Lua, this function may trigger a metamethod for the "newindex" event (see §2.4).

**Comment by siffiejoe** [comment]
First shot available now.
