### ISSUE TITLE
table.maxn

### ISSUE THREAD

**Issue by EPuncker** [keplerproject/lua-compat-5.3#56]
`table.maxn` was deprecated at 5.2, does it have any alternative?

Some people says this is fine:

`table.maxn = function(t) return #t end`

But others disagree, so I'm lost.

**Comment by daurnimator** [comment]
> `table.maxn = function(t) return #t end`
> 
> But others disagree, so I'm lost.

`table.maxn` is literally:
```lua
function maxn(t)
    local max = 0
    for k in pairs(t) do
        if type(k) == "number" and k > max then
            max = k
        end
    end
end
```

Note that lua-compat-5.3 is to make lua 5.1/5.2 act like lua 5.3; not the other way around.

**Comment by EPuncker** [comment]
> ```lua
>             
> ```

thank you
